version: "2"
services:
  etherpad:
    image: moss/etherpad:1.6.0-2
    environment:
      DEBUG_ENTRYPOINT: 'true'
      EP_TITLE: Etherpad
      ADMIN_PASS: admin
      DB_NAME: etherpad
      DB_USER: etherpaduser
      DB_PASS: password
      DB_HOST: mysql
      DB_TYPE: mysql
      FAVICON_URL: "https://www.rcsl.lu/favicon.ico"
      LDAP_ENABLED: 'true'
      LDAP_SERVER: "ldap://dcrcsl01.rcsl.lu"
      LDAP_BIND_DN: "cn=AdminCTG,ou=OU_Users_Luxembourg,ou=OU_RCS_LUXEMBOURG,dc=rcsl,dc=lu"
      LDAP_BIND_PASSWORD: 'Ctgsup*0322'
      LDAP_SEARCH_BASE: "dc=rcsl,dc=lu"
      LDAP_SEARCH_PROPERTY: 'sAMAccountName'
      LDAP_FULL_NAME_PROPERTY: 'cn'
      LDAP_GROUP_SEARCH_BASE: "dc=rcsl,dc=lu"
      LDAP_GROUP_NAME: "CN=GGLUXRCS_Users"
      ANONYMOUS_READONLY: 'false'
    ports:
        - 9001:9001
  mysql:
    image: mysql
    environment:
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: etherpad
      MYSQL_USER: etherpaduser
      MYSQL_ROOT_PASSWORD: mysecret
      