# Generated by Django 2.0.1 on 2018-01-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphqlendpoint', '0026_auto_20180106_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
